# Project information
site_name: SIM 1.0 KR
docs_dir: '../../docs/ko'
site_dir: '../../site'
site_url: https://morai-docs.github.io/sim1.0/site
site_author: MORAI Engineering Service Team
site_description: Release Documentation for MORAI SIM 1.0 KR
site_author: MORAI Engineering Service Team

# Repository
repo_name: morai-docs/sim1.0
repo_url: https://github.com/morai-docs/sim1.0

copyright: Copyright &copy; 2023 <a href="https://www.morai.ai">MORAI Inc.</a> Maintained by the <a href="https://github.com/morai-docs">MORAI-Docs Team.</a>


# Configuration
theme:
  name: material
  custom_dir: '../../material/.overrides'
  logo: assets/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: sans-serif
    code: Roboto Mono
  favicon: assets/Favicon.png
  icon:
    logo: logo
  language: ko

# Plugins
plugins:
  - search:
      lang: ko
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
# hooks:
#   - material/.overrides/hooks/translations.py


# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/morai-docs

  alternate:
    - name: Korean
      link: /sim1.0/site/
      lang: ko

    - name: English
      link: /sim1.0/site/en/ 
      lang: en

extra_css:
  - extra.css


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables


# Page tree
nav:
  - Home: index.md

  - Getting Started:
    - getting-started/index.md
    - getting-started/requirements.md
    - getting-started/execution.md
    - getting-started/running-issue.md

  - User Guide:
    - user-guide/index.md

    - About this Document: user-guide/about/index.md

    - SIM Drive:
      - user-guide/simdrive/index.md

      - Release Note: user-guide/simdrive/release-notes.md

      - User Interface: 
        - user-guide/simdrive/ui/index.md
        - user-guide/simdrive/ui/default.md
        - 계기 정보 UI: user-guide/simdrive/ui/instruments.md
        - 차량 정보 UI: user-guide/simdrive/ui/instruments.md

      - How to Use:
        - user-guide/simdrive/how/index.md
        - Basic Controls: user-guide/simdrive/how/basic-controls.md
        - Sensor Settings: user-guide/simdrive/how/sensors.md
        - user-guide/simdrive/how/useful.md

    - SIM Air: 
      - user-guide/simair/index.md

      - User Interface: 
        - user-guide/simair/ui/index.md
        - user-guide/simair/ui/default.md
        - user-guide/simair/ui/instruments.md

      - How to Use:
        - user-guide/simair/how/index.md
        - Basic Controls: user-guide/simair/how/basic-controls.md
        - Sensor Settings: user-guide/simair/how/sensors.md
        - user-guide/simair/how/useful.md

    - SIM Robotics: 
      - user-guide/simrobot/index.md

    - SIM Maritime: 
      - user-guide/simmari/index.md

  - Developer Guide: 
    - developer-guide/index.md

  - API Guide:
    - api-guide/index.md


 


